#!/bin/bash

# Shows MAC, IP address and any hostname info for all connected wifi devices
# written for openwrt 12.09 Attitude Adjustment

. /home/steve/bin/inc/colours

echo    "# All connected wifi devices, with IP address,"
echo    "# hostname (if available), and MAC address."
echo -e "#" "$BWHITE" "IP address\t name\t\t  MAC address \t\tnote $NORM"
## list all wireless network interfaces
## (for MAC80211 driver; see wiki article for alternative commands)
#for interface in `iw dev | grep Interface | cut -sf 2 -d" "`
#do
interface='wlan0'
  ## for each interface, get mac addresses of connected stations/clients
  maclist=`iw dev $interface station dump | grep Station | cut -f 2 -s -d" "`
  ## for each mac address in that list...
  for mac in $maclist
  do
    ## If a DHCP lease has been given out by dnsmasq,
    ## save it.
    ip="UNKN"
    host=""
    src='/var/lib/misc/dnsmasq.leases'
    ip=`cat /var/lib/misc/dnsmasq.leases | cut -f 2,3,4 -s -d" " | grep $mac | head -1 | cut -f 2 -s -d" "`
    host=`cat /var/lib/misc/dnsmasq.leases | cut -f 2,3,4 -s -d" " | grep $mac | head -1 | cut -f 3 -s -d" "`
    if [ -z $host ]
    then
        ip=`arp -an | grep $mac | head -1 | cut -sf 2 -d" " | sed 's/[()]//g'`
        host=`arp -a | grep $mac | head -1 | cut -sf 1 -d" "`
	src='arp mac matching'
    fi
    # ... show the mac address:
    printf '%-16s %-16s %s \t%s \n'  "$ip" "$host" "$mac" "$src"
  done | sort -nt. -k1 -k4
#done
